---
title: "Git R Done!"
author: "Jeff Yeazell, P.E."
date: "8/2/2019"
output: 
  ioslides_presentation:
    css: my-style.css
    logo: images/Git-Icon-1788C.png
    self_contained: no
    incremental: false
---

# Overview

## Goals 

### You will learn:

- Tools for finding bugs & diagnosing errors in Shiny applications
- Little-known ways to look under the covers 
- How to debug problems in deployed apps
- Cheat code for IDE JavaScript debug tools

## Outline

### We'll cover four main areas:

- Basic Workflow
- Repositories 
- Undo
- Working With Branches

# Basic Workflow

## What Is A Version Control System (VCS)?

* Tool that manages changes made to files and directories in a project
* Git is a VCS
* Nothing that is saved to Git is ever lost
* Git automatically notifies you when your work conflicts with someone else's
    + Harder to accidentally overwrite someone else's work
* Git provides the ability to synchronize work done by different people on different PCs

## Where Does Git Store Information?

* A Git Project has two parts:
    * Files and directories you create and edit directly
    * The extra info that Git records about the project history
* Combined, these two parts make up a __repository__ (repo)
* Git stores its info in the `.git` directory at the root directory of project
* NEVER EDIT OR DELETE THIS DIRECTORY OR ITS CONTENTS!

## Checking The State of a Git Repo

Dummy text

## Viewing What You've Changed

Dummy text
